### ISSUE TITLE
Error when a map only has one level

### ISSUE THREAD

**Issue by agar3s** [StudioKrok/bomberbotmazes_phaser_plugin#1]
The following error is triggered:
Uncaught TypeError: Cannot read property 'isItem' of nullbomberbotMazesPlugin.js:1016 Phaser.Plugin.BomberbotMazes.movementCompleted
When the input map is the following
```
[[
  [1,1,1,1,1],
  [1,1,1,1,1],
  [1,1,1,1,1],
  [1,1,1,1,1],
  [1,1,1,1,1]
]]
```

**Comment by mapedorr** [comment]
Solucionado. Aún sin subir.

**Comment by mapedorr** [comment]
Solucionado en commit: 84ba1e6c25b9d2d7c7b33bb820d2e1884e467701
